### ISSUE TITLE
Extend to handle Controller

### ISSUE THREAD

**Issue by mcondarelli** [edouardswiac/zerotier-api-java#1]
I am interested to extend this to handle also a custom (private) controller.
Are You interested?
Should I send a pull-request or should I fork the project?
I am writing small java programs to act as front-ends to manage my zerotier node, which is also a private controller. If You want I can contribute also those parts.

**Comment by edouardswiac** [comment]
Please submit a PR with your changes to handle the controller. As long as your changes are not specific to your implementation then it will make it.
We can also look at your other code ("those parts") after the PR.

Thanks for contributing!
